controllers/auth.py
from flask import Blueprint, request, render_template, flash, redirect, url_for, session
from models import db, User, Lot, Spot, Reserve
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import func

api = Blueprint('auth', __name__)

@api.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        user = User.query.filter_by(email=email).first()

        if not user:
            flash("User does not exist.")
            return redirect(url_for('auth.login'))

        if not check_password_hash(user.password, password):
            flash("Incorrect password.")
            return redirect(url_for('auth.login'))
        
        session['user_id'] = user.id
        session['is_admin'] = user.is_admin
        session['username'] = user.name
        
        if user.is_admin:
            return redirect(url_for('auth.admin_dashboard'))
        else:
            return redirect(url_for('auth.user_dashboard')) 

    return render_template("login.html")


@api.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        name = request.form.get("name")
        email = request.form.get("email")
        password = request.form.get("password")
        phone = request.form.get("phone")
        address = request.form.get("address")
        pincode = request.form.get("pincode")

        if not email or not password:
            flash("Email and password are required.")
            return redirect(url_for('auth.register'))

        if User.query.filter_by(email=email).first():
            flash("Email already registered.")
            return redirect(url_for('auth.register'))

        new_user = User(
            name=name,
            email=email,
            password=generate_password_hash(password),
            phone=phone,
            address=address,
            pincode=pincode
        )

        db.session.add(new_user)
        db.session.commit()

        flash("Registration successful! Please log in.")
        return redirect(url_for('auth.login'))

    return render_template("register.html")

@api.route("/admin/dashboard")
def admin_dashboard():
    user_id = session.get("user_id")
    user = User.query.get(user_id)
    lots = Lot.query.filter_by(is_active=True).all()
    return render_template("admin/dashboard.html", lots=lots, user=user, is_admin=True)

@api.route("/edit_profile", methods=["GET", "POST"])
def edit_profile():
    user_id = session.get("user_id")
    if user_id is None:
        flash("You must be logged in to edit your profile.")
        return redirect("/login")

    user = User.query.get_or_404(user_id)

    if request.method == "POST":
        user.name = request.form.get("name")
        user.email = request.form.get("email")
        user.password = generate_password_hash(request.form.get("password")) if request.form.get("password") else user.password
        user.phone = request.form.get("phone")
        user.address = request.form.get("address")
        user.pincode = request.form.get("pincode")

        db.session.commit()
        flash("Profile updated successfully!")
        return redirect(url_for('auth.admin_dashboard' if user.is_admin else 'auth.user_dashboard'))

    return render_template("edit_profile.html", user=user, redirect_url=url_for('auth.admin_dashboard' if user.is_admin else 'auth.user_dashboard'))


@api.route('/admin/add_lot', methods=["GET", "POST"])
def add_lot():
    if request.method == "POST":
        name = request.form.get("name")
        price_per_hour = request.form.get("price")
        address = request.form.get("address")
        pincode = request.form.get("pincode")
        total_spots = request.form.get("max")

        if not name or not price_per_hour or not address or not pincode or not total_spots:
            flash("All fields are required.")
            return redirect(url_for('auth.add_lot'))
        
        try:
            price_per_hour = float(price_per_hour)
            total_spots = int(total_spots)
        except ValueError:
            flash("Price must be a number and total spots must be an integer.")
            return redirect(url_for('auth.add_lot'))

        new_lot = Lot(
            name=name,
            price_per_hour=price_per_hour,
            address=address,
            pincode=pincode,
            total_spots=total_spots
        )

        db.session.add(new_lot)
        db.session.flush()
        
        for i in range(int(total_spots)):
            spot = Spot(
                lot_id=new_lot.id,
                spot_number=f"Spot {i + 1}",
                status=False
            )
            db.session.add(spot)
        db.session.commit()

        flash("Parking lot created successfully!")
        return redirect(url_for('auth.admin_dashboard'))
    return render_template("admin/add_lot.html")

@api.route('/admin/delete_lot/<int:lot_id>')
def delete_lot(lot_id):
    lot = Lot.query.get_or_404(lot_id)
    if any(spot.status for spot in lot.spots):
        flash("Cannot delete lot with occupied spots.")
        return redirect(url_for('auth.admin_dashboard'))

    lot.is_active = False
    db.session.commit()
    flash("Parking lot deactivated successfully!")
    return redirect(url_for('auth.admin_dashboard'))

@api.route('/admin/edit_lot/<int:lot_id>', methods=["GET", "POST"])
def edit_lot(lot_id):
    lot = Lot.query.get_or_404(lot_id)

    if request.method == "POST":

        name = request.form.get("name")
        price_per_hour = request.form.get("price")
        address = request.form.get("address")
        pincode = request.form.get("pincode")
        new_total_spots = request.form.get("max")

        try:
            price_per_hour = float(price_per_hour)
            new_total_spots = int(new_total_spots)
        except ValueError:
            flash("Price must be a number and total spots must be an integer.")
            return redirect(url_for('auth.edit_lot', lot_id=lot_id))

        occupied_count = Spot.query.filter_by(lot_id=lot.id, status=True).count()
        if new_total_spots < occupied_count:
            flash(f"Cannot reduce spots below currently occupied count ({occupied_count}).")
            return redirect(url_for('auth.edit_lot', lot_id=lot_id))
        
        lot.name = name
        lot.price_per_hour = price_per_hour
        lot.address = address
        lot.pincode = pincode

        old_total_spots = lot.total_spots

        if new_total_spots > old_total_spots:
            for i in range(old_total_spots + 1, new_total_spots + 1):
                new_spot = Spot(
                    lot_id=lot.id,
                    spot_number=f"Spot {i}",
                    status=False
                )
                db.session.add(new_spot)

        elif new_total_spots < old_total_spots:
            extra_spots = Spot.query.filter_by(lot_id=lot.id).order_by(Spot.id.desc()).limit(old_total_spots - new_total_spots).all()
            for spot in extra_spots:
                if spot.was_occupied:
                    flash("Cannot reduce spots. One or more of the last spots were already used before.", "danger")
                    return redirect(url_for('auth.edit_lot', lot_id=lot.id))
                db.session.delete(spot)

        lot.total_spots = new_total_spots

        db.session.commit()
        flash("Lot updated successfully!")
        return redirect(url_for('auth.admin_dashboard'))
    
    return render_template("admin/edit_lot.html", lot=lot)

@api.route('/admin/spot/<int:spot_id>')
def view_spot(spot_id):
    spot = Spot.query.get_or_404(spot_id)
    return render_template("admin/view_spot.html", spot=spot)

@api.route("/admin/spot/<int:spot_id>/details")
def view_occupied_spot(spot_id):
    spot = Spot.query.get_or_404(spot_id)

    reservation = Reserve.query.filter_by(spot_id=spot.id).order_by(Reserve.start_time.desc()).first()

    duration = datetime.now() - reservation.start_time
    hours = duration.total_seconds() / 3600
    estimated_cost = round(hours * reservation.cost_per_hour, 2)
    

    return render_template("admin/view_occupied_spot.html", reservation=reservation, estimated_cost=estimated_cost)

@api.route('/admin/spot/<int:spot_id>/delete', methods=["POST"])
def delete_spot(spot_id):
    spot = Spot.query.get_or_404(spot_id)

    if spot.status:
        flash("Cannot delete occupied spot.")
        return redirect(url_for('auth.view_spot', spot_id=spot.id))

    if spot.was_occupied:
        flash("Cannot delete this spot. It has been used before.", "warning")
        return redirect(url_for('auth.view_spot', spot_id=spot.id))
    
    lot = spot.lot
    db.session.delete(spot)
    lot.total_spots -= 1
    db.session.commit()

    flash("Spot deleted successfully.")
    return redirect(url_for('auth.admin_dashboard'))

@api.route("/admin/dashboard/users")
def admin_users():
    users = User.query.all()
    return render_template("admin/users.html", users=users)

@api.route("/admin/user/<int:user_id>/reservations")
def user_parking_history(user_id):
    user = User.query.get_or_404(user_id)
    
    reservations = [
        {
            "id": r.id,
            "location": r.spot.lot.name,
            "address": r.spot.lot.address,
            "pincode": r.spot.lot.pincode,
            "vehicle_number": r.vehicle_number,
            "start_time": r.start_time,
            "end_time": r.end_time,
            "cost_per_hour": r.cost_per_hour
        }
        for r in Reserve.query.filter_by(user_id=user_id).order_by(Reserve.start_time.desc()).all()
    ]

    return render_template("admin/user_history.html", user=user, reservations=reservations)

@api.route("/admin/dashboard/search")
def admin_search():
    filter_by = request.args.get("filter_by")
    query = request.args.get("query")
    results = []

    if filter_by and query:
        if filter_by == "spot_id":

templates/dash_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% block title %}
        🚗 Park-Karo! - Dashboard
        {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    {% block styles %}{% endblock %}
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<body>
{% set is_admin = session.get('is_admin') %}
{% set current_path = request.path %}
<nav class="navbar navbar-expand-lg" style="background-color: #ffc800; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.264); position: relative;">
  <div class="container-fluid">
    {% if is_admin %}
    <a class="navbar-brand text-dark fw-bold" href="/admin/dashboard">🚗 Park-Karo!</a>
    <p class="text-danger lead ms-2 mb-0">Admin</p>
    {% else %}
    <a class="navbar-brand text-dark fw-bold" href="/user/dashboard">🚗 Park-Karo!</a>
    {% if user is defined %}
    <p class="text-dark lead ms-2 mb-0">Welcome, {{user.name}}</p>
    {% endif %}
    {% endif %}
    <div class="navbar-center position-absolute top-50 start-50 translate-middle">
      <ul class="navbar-nav d-flex flex-row gap-4">
      <li class="nav-item">
        <a class="nav-link fw-bold text-dark 
          {% if (is_admin and current_path == '/admin/dashboard') 
              or (not is_admin and current_path == '/user/dashboard') %}
              active bg-secondary rounded
          {% endif %}" 
          href="{{ '/admin/dashboard' if is_admin else '/user/dashboard' }}">
          Home
        </a>
      </li>
      {% if not is_admin %}
        <li class="nav-item">
          <a class="nav-link fw-bold text-dark {% if current_path == '/user/reservations' %}active bg-secondary rounded{% endif %}" href="/user/reservations">My Reservations</a>
        </li>
      {% endif %}

      {% if is_admin %}
        <li class="nav-item">
          <a class="nav-link fw-bold text-dark {% if current_path == '/admin/dashboard/users' %}active bg-secondary rounded{% endif %}" href="/admin/dashboard/users">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link fw-bold text-dark {% if current_path == '/admin/dashboard/search' %}active bg-secondary rounded{% endif %}" href="/admin/dashboard/search">Search</a>
        </li>
      {% endif %}

      <li class="nav-item">
        <a class="nav-link fw-bold text-dark 
          {% if current_path == ('/admin/dashboard/summary' if is_admin else '/user/dashboard/summary') %}
            active bg-secondary rounded
          {% endif %}" 
          href="{{ '/admin/dashboard/summary' if is_admin else '/user/dashboard/summary' }}">
          Summary
        </a>
      </li>
      </ul>
    </div>
        
    <ul class="navbar-nav ms-auto ">
      <li class="nav-item dropdown">
        <a class="nav-link text-dark" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-person-fill"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
          <li><a class="dropdown-item" href="{{ url_for('auth.edit_profile') }}">Edit Profile</a></li>
          <li><a class="dropdown-item text-danger" href="/">Logout</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}
<div class="container mt-4">
    {% block content %}
    
    {% endblock %}
</div>
</body>
</html>

templates/edit_profile.html
{% extends "dash_layout.html" %}
<title>
  {% block title %}
  🚗 Park-Karo! - Edit Profile
  {% endblock %}
</title>

{% block content %}
<div class="container d-flex justify-content-center">
    <div class="card shadow p-4 w-100" style="max-width: 420px;">
        <h3 class="h2 mb-3 fw-normal text-center">Edit Profile</h3>
    <form method="POST">
      <div class="form-floating mb-3">
        <input type="text" class="form-control" id="userID" value="{{ user.id }}" readonly>
        <label for="userID">User ID</label>
      </div>
      <div class="form-floating mb-3">
        <input type="text" class="form-control" id="name" name="name" value="{{ user.name }}" required>
        <label for="name">Name</label>
      </div>
      <div class="form-floating mb-3">
        <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" required>
        <label for="email">Email</label>
      </div>
      <div class="form-floating mb-3">
      <input type="password" class="form-control" id="password" name="password" required>
      <label for="password">Password</label>
      </div>
      <div class="form-floating mb-3">
        <input type="text" class="form-control" id="phone" name="phone" value="{{ user.phone }}">
        <label for="phone">Phone</label>
      </div>
      <div class="form-floating mb-3">
        <input type="text" class="form-control" id="address" name="address" value="{{ user.address }}">
        <label for="address">Address</label>
      </div>
      <div class="form-floating mb-4">
        <input type="text" class="form-control" id="pincode" name="pincode" value="{{ user.pincode }}">
        <label for="pincode">Pincode</label>
      </div>

      <div class="row">
        <div class="col">
          <button class="w-100 btn btn-warning" type="submit">Save Changes</button>
        </div>
        <div class="col">
          <a href="{{ redirect_url }}" class="w-100 btn btn-secondary">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block styles %}
<style>
  body {
    background-color: #ebebeb;
  }
  .card {
    border-radius: 1rem;
  }
</style>
{% endblock %}

templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="text-center">
    <h1 class="mb-4">🚗 Park-Karo!</h1>
    <p class="mb-4 lead"> <em>"Ab wait na karo, bas Park Karo!"</em></p>
    <a href="/login" class="btn btn-primary btn-warning w-100 mb-2">Login</a>
    <a href="/register" class="btn btn-primary btn-warning w-100">Register</a>
    <p class="mt-5 mb-0 text-muted"><small>By Vighnesh Sajeev</small></p>
</div>
{% endblock %}

{% block styles %}
<style>
  body {
    background-color: #ebebeb;
  }
  .card {
    border-radius: 1rem;
  }
</style>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {% block title %}
        🚗 Park-Karo!
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    
    {% block styles %}{% endblock %}
    
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh;">
        <div class="card shadow p-4 w-100" style="max-width: 420px;">
            <div class="card-body">
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="alert alert-warning" role="alert">
                    {{ messages[0] }}
                    </div>
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
                {% block scripts %}{% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

templates/login.html
{% extends "layout.html" %}
<title>
    {% block title %}
    🚗 Park-Karo! - Login
    {% endblock %}
</title>
{% block content %}
<h1 class="text-center">
  <a href="/" class="text-dark text-decoration-none">🚗 Park-Karo!</a>
</h1>
<h3 class="h2 mt-5 mb-3 fw-normal text-center">Sign in</h3>
<form method="POST">
    <div class="form-floating">
      <input type="email" class="form-control" id="floatingEmail" name="email" placeholder="Email ID" required>
      <label for="floatingEmail">Email</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password" required>
      <label for="floatingPassword">Password</label>
    </div>
<p class="mt-3 text-center text-muted">
  <small>Don't have an account?
  <a href="/register" class="text-decoration-none">Register</a>
  </small>
</p>
<button class="w-100 btn btn-success btn-primary mt-3" type="submit">Login</button>
</form>
{% endblock %}

{% block styles %}
<style>
  body {
    background-color: #ebebeb;
  }
  .card {
    border-radius: 1rem;
  }
</style>
{% endblock %}

templates/register.html
{% extends "layout.html" %}
<title>
    {% block title %}
    🚗 Park-Karo! - Register
    {% endblock %}
</title>
{% block content %}
<h1 class="text-center">
  <a href="/" class="text-dark text-decoration-none">🚗 Park-Karo!</a>
</h1>
<h3 class="h2 mt-5 mb-3 fw-normal text-center">Sign Up</h3>
<form method="POST">
    <div class="form-floating">
      <input type="name" class="form-control" id="floatingName" name="name" placeholder="Full Name" required>
      <label for="floatingName">Full Name</label>
    </div>
    <div class="form-floating">
      <input type="email" pattern=".+@.+\.com" class="form-control" id="floatingEmail" name="email" placeholder="Email ID" required>
      <label for="floatingEmail">Email</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password" required>
      <label for="floatingPassword">Password</label>
    </div>
    <div class="input-group">
      <span class="input-group-text">+91</span>
      <div class="form-floating flex-grow-1">
        <input type="tel" class="form-control" id="floatingPhone" name="phone" placeholder="Phone number" required pattern="[0-9]{10}" maxlength="10" title="Phone number must be exactly 10 digits"required>
        <label for="floatingPhone">Phone number</label>
      </div>
    </div>
    <div class="form-floating">
      <input type="text" class="form-control" id="floatingAddress" name="address" placeholder="Address" required>
      <label for="floatingAddress">Address</label>
    </div>
    <div class="form-floating mb-3">
      <input type="text" class="form-control" id="floatingPincode" name="pincode" placeholder="Pincode" required>
      <label for="floatingPincode">Pincode</label>
    </div>
    
<p class="mt-3 text-center text-muted">
  <small>Already have an account?
  <a href="/login" class="text-decoration-none">Login</a>
  </small>
</p>
<button class="w-100 btn btn-success btn-primary mt-3" type="submit">Register</button>
</form>
{% endblock %}

{% block styles %}
<style>
  body {
    background-color: #ebebeb;
  }
  .card {
    border-radius: 1rem;
  }
</style>
{% endblock %}